#!/bin/bash
#
# scratch - create a scratch file to dump random thoughts

SCRATCH_DIR=~/scratch

name="$(date +%Y%m%d-%H%M%S)"
ext=""

if [ -n "$1" ]; then
    if [[ "$1" =~ ^\..+ ]]; then
        ext="$1"
    else
        name="$1"
    fi
fi

vim "$SCRATCH_DIR/$name$ext"
