#!/bin/bash

if ! command -v wkhtmltopdf &> /dev/null; then
    echo "Please install wkhtmltopdf in order to convert to PDF."
    exit 1
fi

if [ -z "$1" ]; then
    echo USAGE: topdf INPUT_FILE
    exit 1
fi

IN_FILE=$1
FILENAME=$(basename -- "$IN_FILE")
OUT_FILE="${FILENAME%.*}".pdf

echo Converting "$IN_FILE" to "$OUT_FILE"...

pandoc -s --pdf-engine=wkhtmltopdf -V margin-left:1in -V margin-right:1in -V margin-top:1in -V margin-bottom:1in -o "$OUT_FILE" "$IN_FILE"

